kaitor/blueprints/main.py
import functools

from flask import (Blueprint, flash, g, jsonify, redirect, render_template,
                   request, session, url_for)

from ..models import *

bp = Blueprint('kaitor', __name__, url_prefix='/kaitor/', template_folder="../templates/", static_folder="../static/")
S = db.session 

from . import admin, group, user

bp.register_blueprint(admin.bp)
bp.register_blueprint(group.bp)
bp.register_blueprint(user.bp)


@bp.route("/", methods=["GET"])
def main():
    groups = S.query(Group).all()

    return render_template("select_group.html", groups=groups)

@bp.route("/help")
def instructions():
    return render_template("instructions.html")

kaitor/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>

    <link rel="shortcut icon" href="{{ url_for('kaitor.static', filename='favicon.ico') }}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css" />


    {% block head %} {% endblock %}
    <style></style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-2">
      <div class="container-fluid">
        {% if user %}
        <a class="navbar-brand" href="{{ url_for('kaitor.user.main', token=user.token) }}">
          Solo Problemi: {{ user.name }}
        </a>
        {% else %}
        <a class="navbar-brand" href="{{ url_for('kaitor.main') }}"> Solo Problemi </a>
        {% endif %}
        <div class="ml-auto">
          <a class="btn btn-outline-primary" href="{{ url_for('kaitor.instructions') }}">
            <i class="bi bi-book">&nbsp;Istruzioni</i>
          </a> {% if user %}
          <a class="btn btn-outline-danger" href="{{ url_for('kaitor.main') }}">
            <i class="bi bi-box-arrow-right">&nbsp;Esci</i>
          </a>{% endif %}
        </div>
        
      </div>
    </nav>

    <main class="container mt-5">{% block content %} {% endblock %}</main>

    {% block postscript %}{% endblock %}

    <script
      src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
      integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
      crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"></script>
  </body>
</html>

kaitor/templates/instructions.html
{% extends "base.html" %} {% block title %}Istruzioni per l'uso{% endblock %} {% block head %}
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
  integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
  crossorigin="anonymous" />
<script
  defer
  src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"
  integrity="sha384-XjKyOOlGwcjNTAIQHIpgOno0Hl1YQqzUOEleOLALmuqehneUG+vnGctmUb0ZY0l8"
  crossorigin="anonymous"></script>
<script
  defer
  src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"
  integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05"
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/marked@3.0.2/marked.min.js"></script>
<script src="https://unpkg.com/htmx.org@1.7.0/dist/htmx.min.js"></script>
<style>
    pre {
        white-space: pre-wrap;       /* Since CSS 2.1 */
        white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
        white-space: -pre-wrap;      /* Opera 4-6 */
        white-space: -o-pre-wrap;    /* Opera 7 */
        word-wrap: break-word;
    }

    .col {
        max-width: 49%;
    }
</style>
{% endblock %}

{% block content %}
<div id="sourceDiv">

# Come funziona questa faccenda

Si entra scegliendo la propria classe e poi il proprio nome. Se una password non è stata ancora scelta, si entra con qualsiasi password ma c'è la possibilità di impostarne una, per poi essere i soli ad entrare. Se per qualche motivo non funziona o si dimentica la password, basta avvisare e la resettiamo.

Quando si è dentro, c'è una lista dei problemi. Ciascuno inserisce la propria soluzione, prima della data stabilita. C'è un riquadro che mostra l'anteprima della propria soluzione, mentre la scriviamo, per controllare se il codice markdown o katex è corretto. Più sotto c'è qualche suggerimento su come usare questi due linguaggi.

Dopo la data per inviare la soluzione, è richiesto a ognuno di comparare due soluzioni date da altri due studenti e scegliere quale è migliore. Oltre a scegliere quale è meglio, bisogna anche spiegare perché è meglio.

Dopo la data prevista per confrontare le soluzioni degli altri, otteniamo un riscontro sulla nostra soluzione e su come è stata valutata dagli altri.

# Guida a Markdown

Markdown è un linguaggio di formattazione leggero che permette di scrivere in modo semplice e formattato per la 
visualizzazione online. Ecco alcuni esempi di formattazione comune:

<div class="row my-3"><div class="col border m-1"><pre><code>
Puoi creare titoli e sezioni aggiungendo il simbolo di hashtag (#) all'inizio di una riga:</code></pre><pre><code># Titolo principale
## Sottotitolo
### Sottotitolo di livello 2
</code></pre></div><div class="col border m-1">
Puoi creare titoli e sezioni aggiungendo il simbolo di hashtag (#) all'inizio di una riga:

# Titolo principale
## Sottotitolo
### Sottotitolo di livello 2
</div></div>


<div class="row my-3"><div class="col border m-1"><pre><code>
Puoi creare paragrafi separando parti di testo da una linea vuota e, all'interno di un paragrafo, rendere il testo 
in grassetto o corsivo utilizzando gli asterischi (*):</code></pre><pre><code>Questo è un paragrafo con del **testo in grassetto**.</code></pre><pre><code>Queste sono due linee di testo,
ma un unico paragrafo con del *testo in corsivo*.
</code></pre></div><div class="col border m-1">
Puoi creare paragrafi separando parti di testo da una linea vuota e, all'interno di un paragrafo, rendere il testo 
in grassetto o corsivo utilizzando gli asterischi (*):

Questo è un paragrafo con del **testo in grassetto**.

Queste sono due linee di testo,
ma un unico paragrafo con del *testo in corsivo*.
</div></div>


<div class="row my-3"><div class="col border m-1"><pre><code>
Puoi creare liste puntate o numerate facilmente:</code></pre><pre><code>- Elemento della lista
- Altro elemento della lista</code></pre><pre><code>1. Elemento numerato
2. Altro elemento numerato
</code></pre></div><div class="col border m-1">

Puoi creare liste puntate o numerate facilmente:   
 
- Elemento della lista
- Altro elemento della lista

1. Elemento numerato
2. Altro elemento numerato
</div></div>


<div class="row my-3"><div class="col border m-1"><pre><code>
Non c'è ragione di farlo per la soluzione ad un problema, ma si può inserire un [link a qualche sito](https://it.wikipedia.org/wiki/Giuseppe_Peano) all'interno del testo.
</code></pre></div><div class="col border m-1">

Non c'è ragione di farlo per la soluzione ad un problema, ma si può inserire un [link a qualche sito](https://it.wikipedia.org/wiki/Giuseppe_Peano) all'interno del testo.
</div></div>


<div class="row my-3"><div class="col border m-1"><pre><code>
Si può aggiungere un immagine 
allo stesso modo dei link,
ma con un punto esclamativo davanti:</code></pre><pre><code>![Descrizione](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Vintage_car_meets_world_heritage_site.jpg/320px-Vintage_car_meets_world_heritage_site.jpg)
</code></pre></div><div class="col border m-1">
Si può aggiungere un immagine 
allo stesso modo dei link,
ma con un punto esclamativo davanti:

![Descrizione](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Vintage_car_meets_world_heritage_site.jpg/320px-Vintage_car_meets_world_heritage_site.jpg)
</div></div>


<div class="row my-3"><div class="col border m-1"><pre><code>
Puoi inserire codice senza farlo formattare utilizzando tre backtick</code></pre><pre><code>```</code></pre><pre><code>Testo da **non formattare**</code></pre><pre><code>```</code></pre></div><div class="col border m-1">

Puoi inserire codice senza farlo formattare utilizzando tre backtick

```
Testo da **non formattare**
```
</div></div>


# Formule con KaTeX
Con KaTeX (un motore LaTeX per browser) puoi inserire formule matematiche nel testo.


<div class="row my-3"><div class="col border m-1"><pre><code>
Se vuoi la formula resti nel flusso naturale del testo, come ad esempio $x^2 + 3x - 5 = 0$, usa un singolo $ per racchiudere il codice.
</code></pre></div><div class="col border m-1">
Se vuoi la formula resti nel flusso naturale del testo, come ad esempio $x^2 + 3x - 5 = 0$, usa un singolo $ per racchiudere il codice.
</div></div>

<div class="row my-3"><div class="col border m-1"><pre><code>
Se vuoi che la formula stia su una linea a se stante, come
$$ \lim_{x \to \infty} \frac{\cos(x)}{1 + x^2} $$
usa un doppio dollaro $$.
</code></pre></div><div class="col border m-1">
Se vuoi che la formula stia su una linea a se stante, come
$$ \lim_{x \to \infty} \frac{\cos(x)}{1 + x^2} $$
usa un doppio dollaro $$.
</div></div>


<div class="row my-3"><div class="col border m-1"><pre><code>
Si possono usare le operazioni elementari $1 + 2 - 3 \cdot 4 / 5$, esponenti $x^2$ e indici $A_4$. Frazioni $\frac{4}{5}$ e radici $\sqrt{7}$, anche non quadrate $\sqrt[3]{x+1}$. Tutte le lettere greche, basta precederle con un backslash $\alpha, \beta, \gamma, \dots, \omega$ e anche maiuscole $\Sigma, \Omega$.
</code></pre></div><div class="col border m-1">
Si possono usare le operazioni elementari $1 + 2 - 3 \cdot 4 / 5$, esponenti $x^2$ e indici $A_4$. Frazioni $\frac{4}{5}$ e radici $\sqrt{7}$, anche non quadrate $\sqrt[3]{x+1}$. Tutte le lettere greche, basta precederle con un backslash $\alpha, \beta, \gamma, \dots, \omega$ e anche maiuscole $\Sigma, \Omega$.
</div></div>


<div class="row my-3"><div class="col border m-1"><pre><code>
C'è tutta una scelta di simboli grandi
$$ \sum_{i=1}^n \cos(x-2) \qquad \prod_{n \in \mathbb{N}} \ln\left(\frac{1}{x^7}\right) \qquad \lim_{x \to 0^+} e^{1 / x} \qquad \int_{0}^{\pi} \sin(x) \,dx $$
\quad e \qquad servono a fare uno spazio; \left e \right permettono alle parentesi di avere un'altezza arbitraria.
</code></pre></div><div class="col border m-1">
C'è tutta una scelta di simboli grandi
$$ \sum_{i=1}^n \cos(x-2) \qquad \prod_{n \in \mathbb{N}} \ln\left(\frac{1}{x^7}\right) \qquad \lim_{x \to 0^+} e^{1 / x} \qquad \int_{0}^{\pi} \sin(x) \,dx $$
\quad e \qquad servono a fare uno spazio; \left e \right permettono alle parentesi di avere un'altezza arbitraria.
</div></div>


<div class="row my-3"><div class="col border m-1"><pre><code>
E una sterminata libreria di simboli che non si possono elencare tutti $\tilde{x}$, $\hat{a}$, $\aleph$, $\nabla$, $\hbar$, $\R$, $\mapsto$, $\forall$, etc...
</code></pre></div><div class="col border m-1">
E una sterminata libreria di simboli che non si possono elencare tutti $\tilde{x}$, $\hat{a}$, $\aleph$, $\nabla$, $\hbar$, $\R$, $\mapsto$, $\forall$, etc...
</div></div>

Una lista di tutti (molti? forse non tutti...) i simboli si può trovare sul sito di [katex](https://katex.org/docs/supported.html).
</div>
<hr />
{% endblock %} 

{% block postscript %}
<script>
  const sourceDiv = document.getElementById("sourceDiv");

  // htmx handler for rendering on the client side
  htmx.on("render", function (evt) {
    var element = evt.srcElement;

    var inputContent = (element.value ? element.value : element.innerHTML).trim();
    var markdownContent = marked(inputContent);

    element.innerHTML = markdownContent;

    // Use Katex to render LaTeX formulas
    renderMathInElement(element, {
      delimiters: [
        { left: "$$", right: "$$", display: true },
        { left: "$", right: "$", display: false },
        { left: "\\(", right: "\\)", display: false },
        { left: "\\[", right: "\\]", display: true },
      ],
      throwOnError: false,
    });
  });

  htmx.onLoad(function (evt) {
    htmx.trigger(sourceDiv, "render");
  });
</script>
{% endblock %}

kaitor/templates/select_group.html
{% extends "base.html" %} 

{% block title %}Select Group{% endblock %}


{% block content %}
<form>
  <h1 class="h3 mb-3 fw-normal">Quale classe?</h1>

  <div class="form-floating py-2">
    <select id="groupSelect" class="form-control py-2">
      <option value="" selected disabled>Scegli una classe</option>
      {% for group in groups %}
      <option value="{{ url_for('kaitor.group.select_users', group_id=group.id) }}">{{group.name}}</option>
      {% endfor %}
    </select>
  </div>

  <button id="submitBtn" class="btn btn-primary w-100 py-2" type="submit">Entra</button>
  
</form>
{% endblock %}


{% block postscript %}
<script>
const submitBtn = document.getElementById('submitBtn');

submitBtn.addEventListener('click', (evt) => {
  evt.preventDefault();
  const url = document.getElementById('groupSelect').value;
  window.location.href = url; 
});
</script>
{% endblock %}

kaitor/templates/select_user.html
{% extends "base.html" %}
{% block title %}Authenticate{% endblock %}

{% block content %}
<div id="password-alert"></div>
<form id="authenticateForm">
  <h1 class="h3 mb-3 fw-normal">Quale studente?</h1>

  <div class="form-floating py-2">
    <select id="userSelect" class="form-control py-2">
      <option value="" selected disabled>Scegli il tuo nome</option>
      {% for user in users %}
      <option value="{{user.name}}">{{user.name}}</option>
      {% endfor %}
    </select>
  </div>

  <div class="py-2">
    <input
      type="password"
      class="form-control py-3"
      id="passwordInput"
      placeholder="Password"
    />
  </div>

  <button id="submitBtn" class="btn btn-primary w-100 py-2" type="submit">
    Entra
  </button>
</form>
{% endblock %}

{% block postscript %}
<script>
  const form = document.getElementById("authenticateForm");

  form.addEventListener("submit", (event) => {
    event.preventDefault();

    const username = document.getElementById("userSelect").value;
    const password = document.getElementById("passwordInput").value;
    const user_main = "{{ url_for('kaitor.user.main', token='__token__')}}";

    fetch("{{ url_for('kaitor.group.authenticate', group_id=group.id) }}", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        username: username,
        password: password,
      }),
    })
      .then((response) => response.json())
      .then((data) => {
        if (data.token) {
          console.log(user_main, user_main.replace("<token>", data.token), data);
          window.location.href = user_main.replace("__token__", data.token);
        } else {
          document.getElementById("password-alert").innerHTML = `<div class="alert alert-danger">${data.error}</div>`;
        }
      });
  });
</script>
{% endblock %}

kaitor/templates/user_main.html
{% extends "base.html" %}
{% block title %}{{ user.name }}{% endblock %}
{% block content %}
{% if not user.password %}
<div id="passwordAlert" class="card my-4">
  <div class="card-header text-white bg-danger">
    <h5 class="my-1">Attenzione</h5>
  </div>
  <div class="card-body">
    <!-- <h5 class="card-header">Attenzione</h5> -->
    <p class="card-text">
      È consigliabile impostare una password per proteggere il tuo account da
      birbanti e manigoldi.
    </p>
    <form id="setPasswordForm">
      <div class="form-group my-1">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
        />
      </div>
      <button type="submit" class="btn btn-primary">Imposta Password</button>
    </form>
  </div>
</div>

<div id="password-alert"></div>
{% endif %}

{% if unsolved_problems %}
<div class="row mt-4">
  <h3>Problemi non risolti</h3>
  <ul class="list-group">
    {% for problem in unsolved_problems %}
    <li class="list-group-item">
      (entro {{ problem.date.strftime('%d/%m') }})
      <a href="{{ url_for('kaitor.user.problem.main', token=user.token, problem_id=problem.id) }}">
        {{ problem.short or problem.text[:40]+'...' }}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}

{% if solved_problems %}
<div class="row mt-4">
  <h3>Problemi risolti</h3>
  <ul class="list-group">
    {% for problem in solved_problems %}
    <li class="list-group-item">
      (modificabile)
      <a href="{{ url_for('kaitor.user.problem.main', token=user.token, problem_id=problem.id) }}">
        {{ problem.short }}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}

{% if past_problems %}
<div class="row mt-4">
  <h3>Problemi passati</h3>
  <ul class="list-group">
    {% for problem in past_problems %}
    <li class="list-group-item">
      {% if problem.due_comparison and not problem.comparison %}
      <strong>(da comparare!)</strong>
      {% elif problem.due_comparison and problem.comparison %}
      (comparato)
      {% else %}
      (...passato...)
      {% endif %}
      <a href="{{ url_for('kaitor.user.problem.main', token=user.token, problem_id=problem.id) }}">
        {{ problem.short }}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% endblock %}

{% block postscript %}
{% if not user.password %}
<script>
  const form = document.getElementById("setPasswordForm");
  const password_input = document.getElementById("password");

  form.addEventListener("submit", (event) => {
    event.preventDefault();

    fetch("{{ url_for('kaitor.user.set_password', token=user.token) }}", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        username: "{{ user.name }}",
        new_password: password_input.value
      }),
    })
      .then((response) => response.json())
      .then((data) => {
        let alert = "";
        if (data.message) {
          document.getElementById("passwordAlert").style.display = "none";
          alert = `<div class="alert alert-success">Password set!</div>`;
        } else {
          alert = `<div class="alert alert-danger">${data.error}</div>`;
        }
        document.getElementById("password-alert").innerHTML = alert;
      });
  });
</script>
{% endif %}
{% endblock %}